//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickDBAccess.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickDBAccess.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Connection.
        /// </summary>
        internal static string Form_AddConnectionButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.AddConnectionButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Button Down.
        /// </summary>
        internal static string Form_ButtonsDownButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.ButtonsDownButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Button Up.
        /// </summary>
        internal static string Form_ButtonsUpButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.ButtonsUpButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Connection Down.
        /// </summary>
        internal static string Form_ConnectionsDownButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.ConnectionsDownButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Connection Up.
        /// </summary>
        internal static string Form_ConnectionsUpButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.ConnectionsUpButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Data Source Down.
        /// </summary>
        internal static string Form_DataSourcesDownButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.DataSourcesDownButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Data Source Up.
        /// </summary>
        internal static string Form_DataSourcesUpButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.DataSourcesUpButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Button.
        /// </summary>
        internal static string Form_DeleteButtonButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.DeleteButtonButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Connection.
        /// </summary>
        internal static string Form_DeleteConnectionButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.DeleteConnectionButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Data Source.
        /// </summary>
        internal static string Form_DeleteDataSourceButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.DeleteDataSourceButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Parameter.
        /// </summary>
        internal static string Form_DeleteParameterButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.DeleteParameterButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Parent Paramerter.
        /// </summary>
        internal static string Form_DeleteParentParameterButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.DeleteParentParameterButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Table View.
        /// </summary>
        internal static string Form_DeleteTableViewButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.DeleteTableViewButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Button.
        /// </summary>
        internal static string Form_EditButtonButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.EditButtonButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Connection.
        /// </summary>
        internal static string Form_EditConnectionButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.EditConnectionButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Data Source.
        /// </summary>
        internal static string Form_EditDataSourceButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.EditDataSourceButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Parameter.
        /// </summary>
        internal static string Form_EditParameterButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.EditParameterButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Parent Parameter.
        /// </summary>
        internal static string Form_EditParentParameterButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.EditParentParameterButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Table View.
        /// </summary>
        internal static string Form_EditTableViewButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.EditTableViewButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Button.
        /// </summary>
        internal static string Form_NewButtonButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.NewButtonButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Data Source.
        /// </summary>
        internal static string Form_NewDataSourceButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.NewDataSourceButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Parameter.
        /// </summary>
        internal static string Form_NewParameterButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.NewParameterButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Parent Parameter.
        /// </summary>
        internal static string Form_NewParentParameterButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.NewParentParameterButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Table View.
        /// </summary>
        internal static string Form_NewTableViewButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.NewTableViewButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Parameter Down.
        /// </summary>
        internal static string Form_ParameterDownButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.ParameterDownButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Parameter Up.
        /// </summary>
        internal static string Form_ParameterUpButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.ParameterUpButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Parent Parameter Down.
        /// </summary>
        internal static string Form_ParentParameterDownButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.ParentParameterDownButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Parent Parameter Up.
        /// </summary>
        internal static string Form_ParentParameterUpButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.ParentParameterUpButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Table View Down.
        /// </summary>
        internal static string Form_TableViewsDownButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.TableViewsDownButton.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Table View Up.
        /// </summary>
        internal static string Form_TableViewsUpButton_Tooltip {
            get {
                return ResourceManager.GetString("Form.TableViewsUpButton.Tooltip", resourceCulture);
            }
        }
    }
}
